name: App Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: https://registry.feijoadaserver.com
        username: "admin"
        password: "admin@registry"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: user/app:latest

    - name: Deploy with Docker Compose
      run: docker-compose up -d
