name: App Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Build and push
    #  uses: docker/build-push-action@v5
    #  with:
    #    context: .
    #    file: ./Dockerfile
    #    push: true
    #   tags: ${{ secrets.DOCKER_USER }}/clockbox:latest

    - name: Buildx create
      run: docker buildx create --use

    - name: Buildx inspect
      run: docker buildx inspect --bootstrap

    - name: Buildx build
      run: docker buildx build --push -t localhost:5000/html_app:latest .

    - name: Deploy with Docker Compose
      run: docker-compose up -d

